### ISSUE TITLE
Fehler

### ISSUE THREAD

**Issue by MigosGames** [Uweklaus/homebridge-esp-windowshades#1]
Hallo,

ich bekomme immer den Fehler in Arduino, dass er die Datei Task.h nicht findet.
Woran liegt das? Mache ich etwas falsch? Können Sie mir helfen?

~Michael

**Comment by MigosGames** [comment]
@Uweklaus Haben Sie eine Idde woran es liegen könnte?

**Comment by Uweklaus** [comment]
Hallo, evtl haben Sie die Taskbibliothek nicht in die ide hinzugefügt. 

Makuna/Task
